/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StyleRecommendation = IDL.Record({
  'glasses' : IDL.Vec(IDL.Text),
  'hairstyles' : IDL.Vec(IDL.Text),
  'faceShape' : IDL.Text,
  'shoes' : IDL.Vec(IDL.Text),
  'clothingColors' : IDL.Vec(IDL.Text),
  'skinTone' : IDL.Text,
});

export const idlService = IDL.Service({
  'analyzeImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [StyleRecommendation], []),
  'getRecentRecommendations' : IDL.Func(
      [],
      [IDL.Vec(StyleRecommendation)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StyleRecommendation = IDL.Record({
    'glasses' : IDL.Vec(IDL.Text),
    'hairstyles' : IDL.Vec(IDL.Text),
    'faceShape' : IDL.Text,
    'shoes' : IDL.Vec(IDL.Text),
    'clothingColors' : IDL.Vec(IDL.Text),
    'skinTone' : IDL.Text,
  });
  
  return IDL.Service({
    'analyzeImage' : IDL.Func([IDL.Vec(IDL.Nat8)], [StyleRecommendation], []),
    'getRecentRecommendations' : IDL.Func(
        [],
        [IDL.Vec(StyleRecommendation)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };